nginx:
  container_name: api-pagamentos-nginx
  build: nginx
  command: nginx -g "daemon off;"
  links:
    - php
  ports:
    - "8181:80"
php:
  container_name: api-pagamentos-back-end
  build: php
  volumes:
    - ../:/var/www
  working_dir: /var/www/public
  command: php-fpm
  links:
    - db
  environment:
    APP_ENV: local
    APP_NAME: api-pagamentos
    APP_DEBUG: 'true'
    APP_LOCALE: it
    APP_FALLBACK_LOCALE: it
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
    XDEBUG_CONFIG: remote_host=docker.for.wsl2.host.internal
    PHP_IDE_CONFIG: serverName=localhost
  extra_hosts:
    docker.for.wsl2.host.internal: ${IP}
db:
  container_name: api-pagamentos-bd
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret